### ISSUE TITLE
Can't maintain parity

### ISSUE THREAD

**Issue by GameBully2K** [rajatK012/hashconnectWalletConnect#3]
Each time you visit the site you have to go through the pairing process and it's added as a new DApp

![image](https://user-images.githubusercontent.com/71235565/162793068-90c9c037-c8f0-47a7-aebe-e3c95c56573d.png)

I suspect the problem is in this part of the connect() process

![image](https://user-images.githubusercontent.com/71235565/162793389-dd8ee9fa-6f46-40f0-8227-613ab423369c.png)

**Comment by woodwardmatt** [comment]
@GameBully2K - I was seeing this behavior too. I found that if I updated the following line: 

https://github.com/rajatK012/hashconnectWalletConnect/blob/5f79c02c550672b57e881d3441f3466d719ac6b5/src/HashConnectAPIProvider.tsx#L51

to match the name of the localStorage item (i.e. "hashconnectData" not "  hashConnectData") at:

https://github.com/rajatK012/hashconnectWalletConnect/blob/5f79c02c550672b57e881d3441f3466d719ac6b5/src/HashConnectAPIProvider.tsx#L135

This allowed the localStorage item to be found and therefore load the connection information into the current props / state of the component and maintain the "Connected" state.

Hope that helps :)

**Comment by woodwardmatt** [comment]
Also just to note, that because your not going through re-pairing each time the dApp name does not then get duplicated within HashPack itself.

**Comment by woodwardmatt** [comment]
@rajatK012 - Just put in a PR to fix this typo :)

**Comment by rajatK012** [comment]
Thanks @woodwardmatt  I merged your request

**Comment by GameBully2K** [comment]
thanks @woodwardmatt good obsoveration skills
